// jqwidgets-framework
declare module 'jqwidgets-framework/jqwidgets/jqxcore'
declare module 'jqwidgets-framework/jqwidgets/jqxdata'
declare module 'jqwidgets-framework/jqwidgets/jqxbuttons'
declare module 'jqwidgets-framework/jqwidgets/jqxscrollbar'
declare module 'jqwidgets-framework/jqwidgets/jqxmenu'
declare module 'jqwidgets-framework/jqwidgets/jqxgrid'
declare module 'jqwidgets-framework/jqwidgets/jqxgrid.selection'
declare module 'jqwidgets-framework/jqwidgets/jqxgrid.pager'
declare module 'jqwidgets-framework/jqwidgets/jqxgrid.sort'
declare module 'jqwidgets-framework/jqwidgets/jqxgrid.filter'
declare module 'jqwidgets-framework/jqwidgets/jqx-all'

// jqwidgets-scripts
declare module 'jqwidgets-scripts/jqwidgets/jqxcore'
declare module 'jqwidgets-scripts/jqwidgets/jqxdata'
declare module 'jqwidgets-scripts/jqwidgets/jqxbuttons'
declare module 'jqwidgets-scripts/jqwidgets/jqxscrollbar'
declare module 'jqwidgets-scripts/jqwidgets/jqxlistbox'
declare module 'jqwidgets-scripts/jqwidgets/jqxdropdownlist'
declare module 'jqwidgets-scripts/jqwidgets/jqxmenu'
declare module 'jqwidgets-scripts/jqwidgets/jqxgrid'
declare module 'jqwidgets-scripts/jqwidgets/jqxgrid.selection'
declare module 'jqwidgets-scripts/jqwidgets/jqxgrid.pager'
declare module 'jqwidgets-scripts/jqwidgets/jqxgrid.sort'
declare module 'jqwidgets-scripts/jqwidgets/jqxgrid.filter'
declare module 'jqwidgets-scripts/jqwidgets/jqxgrid.columnsresize'
declare module 'jqwidgets-scripts/jqwidgets/jqxgrid.columnsreorder'
